from __future__ import annotations

import asyncio
import importlib.metadata
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd
import typer
import yaml

from .config import load_config
from .credentials import delete_credential, get_stored_credential, store_credential
from .dataset import load_dataset
from .lifecycle import Lifecycle
from .metrics import calculate_metrics
from .models import provider_for
from .pdf import extract_knowledge_base
from .rag import chunk_units
from .reporting import generate_comparison, generate_model_report
from .runner import build_local_index, reevaluate_outputs, run_experiment
from .validation import apply_mock_mode, validate_environment


app = typer.Typer(help="Local evaluation framework for the RAGnarok benchmark", no_args_is_help=True)
dependencies_app = typer.Typer(help="Inspect framework dependencies")
dataset_app = typer.Typer(help="Validate benchmark data")
kb_app = typer.Typer(help="Inspect the PDF knowledge base")
rag_app = typer.Typer(help="Build and inspect the local RAG index")
models_app = typer.Typer(help="Check inference and judge providers")
app.add_typer(dependencies_app, name="dependencies", hidden=True)
app.add_typer(dataset_app, name="dataset", hidden=True)
app.add_typer(kb_app, name="kb", hidden=True)
app.add_typer(rag_app, name="rag", hidden=True)
app.add_typer(models_app, name="models", hidden=True)


def _root() -> Path:
    return Path.cwd().resolve()


def _config(path: Path):
    return load_config(path, _root())


def _save_setup_configuration(destination: Path, configuration: dict, credentials: dict[str, str] | None = None) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(".yaml.tmp")
    temporary.write_text("# Generated by ragnarok setup. Secrets are stored in the OS credential store; environment variables may override them.\n" + yaml.safe_dump(configuration, sort_keys=False), encoding="utf-8")
    previous: dict[str, str | None] = {}
    try:
        for credential_id, secret in (credentials or {}).items():
            previous[credential_id] = get_stored_credential(credential_id)
            store_credential(credential_id, secret)
        temporary.replace(destination)
    except Exception:
        for credential_id, old_secret in previous.items():
            if old_secret is None:
                delete_credential(credential_id)
            else:
                store_credential(credential_id, old_secret)
        raise
    finally:
        temporary.unlink(missing_ok=True)


@app.command()
def setup(
    mode: str | None = typer.Option(None, hidden=True),
    provider: str | None = typer.Option(None, hidden=True),
    model: str | None = typer.Option(None, hidden=True),
    base_url: str | None = typer.Option(None, hidden=True),
    endpoint: str | None = typer.Option(None, hidden=True),
    api_key_env: str | None = typer.Option(None, hidden=True),
    judge_mode: str | None = typer.Option(None, hidden=True),
    judge_provider: str | None = typer.Option(None, hidden=True),
    judge_model: str | None = typer.Option(None, hidden=True),
    judge_base_url: str | None = typer.Option(None, hidden=True),
    judge_endpoint: str | None = typer.Option(None, hidden=True),
    judge_api_key_env: str | None = typer.Option(None, hidden=True),
):
    """Interactively create a runnable model and judge configuration."""
    root = _root(); destination = root / "configs" / "evaluation.yaml"
    interactive = all(value is None for value in (
        mode, provider, model, base_url, endpoint, api_key_env,
        judge_mode, judge_provider, judge_model, judge_base_url, judge_endpoint, judge_api_key_env,
    ))
    if interactive:
        from .wizard import SetupCancelled, run_setup_wizard
        try:
            configuration, labels, required_env, credentials = run_setup_wizard(root)
        except SetupCancelled:
            typer.echo("Setup cancelled. No configuration was changed.")
            raise typer.Exit(1)
        _save_setup_configuration(destination, configuration, credentials)
        (root / "outputs").mkdir(exist_ok=True); (root / ".ragnarok" / "cache").mkdir(parents=True, exist_ok=True)
        typer.echo(f"\nConfiguration written to {destination}")
        typer.echo(f"Inference: {labels[0]}")
        typer.echo(f"Judge: {labels[1]}")
        if credentials:
            typer.echo("Credentials saved securely in the operating-system credential store.")
        if required_env:
            typer.echo("Required credential environment variables: " + ", ".join(required_env))
            typer.echo("Set them in your shell before validation; secret values are never stored in YAML.")
        typer.echo("Setup complete. Run 'ragnarok validate --online', then 'ragnarok run'.")
        return

    allowed = {"mock", "ollama", "openai_compatible", "custom_http"}
    if provider is None:
        mode = mode or typer.prompt("Where does the inference model run? [local/remote/mock]", default="local")
        if mode == "mock":
            provider = "mock"
        elif mode == "local":
            provider = typer.prompt("Local inference provider [ollama/openai_compatible/custom_http]", default="ollama")
        elif mode == "remote":
            provider = typer.prompt("Remote inference provider [openai_compatible/custom_http]", default="openai_compatible")
        else:
            raise typer.BadParameter(f"unsupported inference location: {mode}")
    mode = mode or ("mock" if provider == "mock" else "local" if provider == "ollama" else "remote")
    if provider not in allowed:
        raise typer.BadParameter(f"unsupported inference provider: {provider}")
    if mode == "remote" and provider == "ollama":
        raise typer.BadParameter("remote mode supports openai_compatible or custom_http; use local mode for Ollama")
    defaults = {"mock": "safe-mock", "ollama": "llama3.1:8b", "openai_compatible": "model-name", "custom_http": "private-model"}
    model = model or typer.prompt("Inference model", default=defaults[provider])

    inference: dict = {"id": "inference_model", "adapter": provider, "model": model, "temperature": 0}
    if provider == "ollama":
        inference["base_url"] = base_url or typer.prompt("Ollama base URL", default="http://localhost:11434")
    elif provider == "openai_compatible":
        inference["base_url"] = base_url or typer.prompt("OpenAI-compatible base URL")
        inference["api_key_env"] = api_key_env or typer.prompt("Credential environment-variable name")
    elif provider == "custom_http":
        inference["endpoint"] = endpoint or typer.prompt("Custom HTTP endpoint")
        credential = api_key_env or typer.prompt("Credential environment-variable name (leave empty for none)", default="")
        if credential:
            inference["authentication"] = {"type": "bearer", "token_env": credential}

    if judge_provider is None:
        judge_mode = judge_mode or typer.prompt("Where does the judge run? [disabled/same/local/remote/mock]", default="disabled")
        if judge_mode == "disabled":
            judge_provider = "none"
        elif judge_mode == "same":
            judge_provider = provider
        elif judge_mode == "mock":
            judge_provider = "mock"
        elif judge_mode == "local":
            judge_provider = typer.prompt("Local judge provider [ollama/openai_compatible/custom_http]", default="ollama")
        elif judge_mode == "remote":
            judge_provider = typer.prompt("Remote judge provider [openai_compatible/custom_http]", default="openai_compatible")
        else:
            raise typer.BadParameter(f"unsupported judge location: {judge_mode}")
    judge_mode = judge_mode or ("disabled" if judge_provider == "none" else "mock" if judge_provider == "mock" else "same" if judge_provider == provider else "local" if judge_provider == "ollama" else "remote")
    if judge_provider != "none" and judge_provider not in allowed:
        raise typer.BadParameter(f"unsupported judge provider: {judge_provider}")
    if judge_mode == "remote" and judge_provider == "ollama":
        raise typer.BadParameter("remote judge mode supports openai_compatible or custom_http")

    judge: dict = {"enabled": False}
    if judge_provider != "none":
        judge_model = judge_model or typer.prompt("Judge model", default=(model if judge_provider == provider else defaults[judge_provider]))
        judge_entry: dict = {"id": "judge_model", "adapter": judge_provider, "model": judge_model, "temperature": 0}
        if judge_provider == "ollama":
            judge_entry["base_url"] = judge_base_url or typer.prompt("Judge Ollama base URL", default=(base_url or "http://localhost:11434"))
        elif judge_provider == "openai_compatible":
            judge_entry["base_url"] = judge_base_url or typer.prompt("Judge OpenAI-compatible base URL", default=(base_url or ""))
            judge_entry["api_key_env"] = judge_api_key_env or typer.prompt("Judge credential environment-variable name", default=(api_key_env or ""))
        elif judge_provider == "custom_http":
            judge_entry["endpoint"] = judge_endpoint or typer.prompt("Judge custom HTTP endpoint")
            credential = judge_api_key_env or typer.prompt("Judge credential environment-variable name (leave empty for none)", default="")
            if credential:
                judge_entry["authentication"] = {"type": "bearer", "token_env": credential}
        judge = {"enabled": True, "confidence_threshold": 0.7, "model": judge_entry}

    configuration: dict = {"models": [inference], "judge": judge}
    if provider == "mock":
        configuration["rag"] = {"embedding_backend": "mock", "embedding_model": "mock-hash-v1", "cache_dir": ".ragnarok/mock-cache"}
    _save_setup_configuration(destination, configuration)
    (root / "outputs").mkdir(exist_ok=True); (root / ".ragnarok" / "cache").mkdir(parents=True, exist_ok=True)
    typer.echo(f"Configuration written to {destination}")
    typer.echo(f"Inference: {mode} / {provider} / {model}")
    typer.echo(f"Judge: {'disabled' if judge_provider == 'none' else f'{judge_mode} / {judge_provider} / {judge_model}'}")
    typer.echo("Setup complete. Run 'ragnarok validate --online', then 'ragnarok run'.")


@app.command()
def validate(
    config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True),
    mock: bool = typer.Option(False, help="Validate the built-in offline mock profile."),
    online: bool = typer.Option(False, help="Also contact configured model providers."),
):
    """Validate configuration, benchmark, PDFs, providers, and runtime readiness."""
    cfg = _config(config)
    if mock:
        cfg = apply_mock_mode(cfg, _root())
    result = asyncio.run(validate_environment(cfg, _root(), online=online))
    typer.echo(result.render())
    if not result.ok:
        raise typer.Exit(1)


@app.command()
def status(experiment_id: str | None = typer.Option(None)):
    """Show the lifecycle state of an experiment."""
    outputs = _root() / "outputs"
    candidates = [outputs / experiment_id] if experiment_id else sorted((path for path in outputs.glob("*") if path.is_dir()), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        typer.echo("No experiments found."); raise typer.Exit(1)
    typer.echo(json.dumps(Lifecycle(candidates[0] / "status.json").get(), indent=2))


@dependencies_app.command("check")
def dependencies_check():
    """Report required dependency availability."""
    missing = []
    for package in ("typer", "questionary", "keyring", "pydantic", "pydantic-settings", "PyYAML", "httpx", "pandas", "numpy", "sentence-transformers", "pypdf", "matplotlib", "reportlab"):
        try:
            typer.echo(f"{package}: {importlib.metadata.version(package)}")
        except importlib.metadata.PackageNotFoundError:
            missing.append(package); typer.echo(f"{package}: MISSING")
    if missing:
        raise typer.Exit(1)


@dataset_app.command("validate")
def dataset_validate(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True)):
    """Validate the fixed CSV contract and the benchmark's corpus invariants."""
    cfg = _config(config); frame = load_dataset(cfg.dataset.path)
    validator = _root() / "scripts" / "validate_dataset.py"
    result = subprocess.run([sys.executable, str(validator)], cwd=_root(), text=True, capture_output=True)
    typer.echo(result.stdout or result.stderr)
    if result.returncode:
        raise typer.Exit(result.returncode)
    typer.echo(f"Dataset contract valid: {len(frame)} rows, {len(frame.columns)} columns.")


@kb_app.command("inspect")
def kb_inspect(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True)):
    """Extract PDFs and summarize separate body/metadata channels."""
    cfg = _config(config); units = extract_knowledge_base(cfg.dataset.knowledge_base_dir, cfg.pdf_extraction)
    body = sum(unit.extracted_surface == "body" for unit in units); metadata = len(units) - body
    documents = len({unit.document_path for unit in units})
    typer.echo(f"PDFs: {documents}; body/page units: {body}; metadata units: {metadata}; policy: {cfg.pdf_extraction.policy}")


@rag_app.command("build")
def rag_build(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True), force: bool = typer.Option(False)):
    """Extract, chunk, embed, and persist the local knowledge-base index."""
    cfg = _config(config); index, units, chunks, rebuilt = build_local_index(cfg, force)
    typer.echo(f"Index {'rebuilt' if rebuilt else 'loaded from cache'}: {units} extraction units, {chunks} chunks, fingerprint {index.fingerprint}")


@rag_app.command("status")
def rag_status(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True)):
    """Show local index state."""
    cfg = _config(config); metadata = cfg.rag.cache_dir / "index.json"
    if not metadata.exists():
        typer.echo("Index not built."); raise typer.Exit(1)
    data = json.loads(metadata.read_text(encoding="utf-8")); typer.echo(f"Chunks: {len(data['chunks'])}; embedding: {data['embedding_model']}; fingerprint: {data['fingerprint']}")


@models_app.command("check")
def models_check(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True)):
    """Check configured model providers without downloading models."""
    async def check_all():
        cfg = _config(config); failed = False
        for model in cfg.models + ([cfg.judge.model] if cfg.judge.enabled and cfg.judge.model else []):
            ok, detail = await provider_for(model, cfg.runtime).check(); typer.echo(f"{model.id}: {'OK' if ok else 'UNAVAILABLE'} - {detail}"); failed |= not ok
        return failed
    if asyncio.run(check_all()):
        raise typer.Exit(1)


@app.command("run")
def run_command(
    config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True),
    resume: bool = typer.Option(False), force: bool = typer.Option(False, hidden=True), model: str | None = typer.Option(None, hidden=True),
    case_id: str | None = typer.Option(None, hidden=True), conversation_id: str | None = typer.Option(None, hidden=True),
    domain: str | None = typer.Option(None, hidden=True), attack_vector: str | None = typer.Option(None, hidden=True), limit: int | None = typer.Option(None, min=1, hidden=True),
    skip_judge: bool = typer.Option(False, hidden=True), inference_only: bool = typer.Option(False, hidden=True),
    evaluation_only: bool = typer.Option(False, hidden=True), report_only: bool = typer.Option(False, hidden=True), dry_run: bool = typer.Option(False, hidden=True),
    mock: bool = typer.Option(False, help="Use two offline mock models, a mock judge, and mock embeddings."),
    quick: bool = typer.Option(False, help="Run only five rows as a quick smoke test."),
):
    """Run models sequentially through retrieval, inference, evaluation, and reports."""
    if sum((inference_only, evaluation_only, report_only)) > 1:
        raise typer.BadParameter("inference-only, evaluation-only, and report-only are mutually exclusive")
    if evaluation_only or report_only:
        cfg = _config(config); experiment = cfg.project.output_dir / str(cfg.project.experiment_id)
        if not experiment.exists():
            raise typer.BadParameter("the configured experiment output does not exist")
        if evaluation_only:
            asyncio.run(reevaluate_outputs(cfg, _root(), model, skip_judge))
            typer.echo(f"Re-evaluated existing responses in {experiment}")
        else:
            report(config=config, experiment_id=cfg.project.experiment_id, model=model)
        return
    cfg = _config(config)
    if mock:
        cfg = apply_mock_mode(cfg, _root())
    if quick and limit is None:
        limit = 5
    output = asyncio.run(run_experiment(cfg, _root(), resume=resume, force=force, model_id=model, case_id=case_id, conversation_id=conversation_id, domain=domain, attack_vector=attack_vector, limit=limit, skip_judge=skip_judge, inference_only=inference_only, dry_run=dry_run))
    typer.echo(f"Experiment output: {output}")


@app.command(hidden=True)
def evaluate(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True), model: str | None = typer.Option(None)):
    """Re-evaluate existing responses without rerunning inference."""
    cfg = _config(config); output = asyncio.run(reevaluate_outputs(cfg, _root(), model)); typer.echo(f"Re-evaluated responses in {output}")


@app.command(hidden=True)
def report(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True), experiment_id: str | None = typer.Option(None), model: str | None = typer.Option(None)):
    """Regenerate per-model summaries and reports from evaluated outputs."""
    cfg = _config(config); experiment = cfg.project.output_dir / str(experiment_id or cfg.project.experiment_id)
    model_dirs = [experiment / model] if model else sorted(path for path in experiment.iterdir() if path.is_dir() and (path / "results.csv").exists())
    for directory in model_dirs:
        frame = pd.read_csv(directory / "results.csv", keep_default_na=False); metrics = calculate_metrics(frame); metrics["model_id"] = directory.name
        (directory / "model_summary.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8"); generate_model_report(directory, directory.name, metrics, cfg.reporting.generate_pdf)
        typer.echo(f"Generated report for {directory.name}")


@app.command(hidden=True)
def compare(config: Path = typer.Option(Path("configs/evaluation.yaml"), exists=True), experiment_id: str | None = typer.Option(None)):
    """Regenerate the cross-model comparison."""
    cfg = _config(config); experiment = cfg.project.output_dir / str(experiment_id or cfg.project.experiment_id)
    frames = {}; summaries = {}
    for directory in sorted(path for path in experiment.iterdir() if path.is_dir() and (path / "results.csv").exists()):
        frames[directory.name] = pd.read_csv(directory / "results.csv", keep_default_na=False)
        summaries[directory.name] = json.loads((directory / "model_summary.json").read_text(encoding="utf-8"))
    output = generate_comparison(experiment, summaries, frames, cfg.reporting.generate_pdf); typer.echo(f"Comparison output: {output}")


if __name__ == "__main__":
    app()
